### ISSUE TITLE
App crash on tablet when changing screen orientation during install

### ISSUE THREAD

**Issue by aaaaalbert** [SensibilityTestbed/sensibility-testbed#18]
As witnessed on an Asus Transformer T700 tablet running Android 4.2.

I think what happened is that I rotated the tablet I installed on while "Unpacking Python...." was still in progress, and then mistook the disappearance of this notification to mean the unpacking is done. I believe the app stopped responding when I then tapped "Install".

I'll try to replicate when I get my hands on that tablet again; feel free to try on your devices too!

(If screen rotations are really the problem, then the fix should be pretty easy, as in: Set the manifest flag that keeps our app from responding to screen orientation changes.)

From the ANR on Google Play:

```
java.lang.IllegalArgumentException: View not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:383)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:285)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
at android.app.Dialog.dismissDialog(Dialog.java:323)
at android.app.Dialog.dismiss(Dialog.java:306)
at com.sensibility_testbed.ScriptActivity$17$1.run(ScriptActivity.java:887)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5039)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aaaaalbert** [comment]
Sensibility Testbed app no longer supports Android 4.2. Closing.
